name: Update gist with latest HackMD notes
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" # update every Sunday at midnight
  workflow_dispatch:
  
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: "Install dependencies"
        run: pip install -r requirements.txt

      - name: "Update gist"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          HACKMD_API_KEY: ${{ secrets.HACKMD_API_KEY }}
        run: python main.py